/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportesRouteImport } from './routes/_app/reportes'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCxcRouteImport } from './routes/_app/cxc'
import { Route as AppClinicaRouteImport } from './routes/_app/clinica'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppCitasRouteRouteImport } from './routes/_app/citas/route'
import { Route as AppTesoreriaIndexRouteImport } from './routes/_app/tesoreria/index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppCitasIndexRouteImport } from './routes/_app/citas/index'
import { Route as AppVentasReportesRouteImport } from './routes/_app/ventas/reportes'
import { Route as AppVentasPrestamosRouteImport } from './routes/_app/ventas/prestamos'
import { Route as AppVentasNuevaRouteImport } from './routes/_app/ventas/nueva'
import { Route as AppVentasFacturasEmitidasRouteImport } from './routes/_app/ventas/facturas-emitidas'
import { Route as AppVentasCuadreDeCajaRouteImport } from './routes/_app/ventas/cuadre-de-caja'
import { Route as AppProveedoresGestionRouteImport } from './routes/_app/proveedores/gestion'
import { Route as AppInventarioUnidadesRouteImport } from './routes/_app/inventario/unidades'
import { Route as AppInventarioTraspasosRouteImport } from './routes/_app/inventario/traspasos'
import { Route as AppInventarioReportesRouteImport } from './routes/_app/inventario/reportes'
import { Route as AppInventarioRecetasRouteImport } from './routes/_app/inventario/recetas'
import { Route as AppInventarioProductosRouteImport } from './routes/_app/inventario/productos'
import { Route as AppInventarioMarcasRouteImport } from './routes/_app/inventario/marcas'
import { Route as AppInventarioLotesRouteImport } from './routes/_app/inventario/lotes'
import { Route as AppInventarioKardexRouteImport } from './routes/_app/inventario/kardex'
import { Route as AppInventarioDepositosRouteImport } from './routes/_app/inventario/depositos'
import { Route as AppInventarioDepartamentosRouteImport } from './routes/_app/inventario/departamentos'
import { Route as AppInventarioComprasRouteImport } from './routes/_app/inventario/compras'
import { Route as AppInventarioAjustesRouteImport } from './routes/_app/inventario/ajustes'
import { Route as AppContabilidadPlanCuentasRouteImport } from './routes/_app/contabilidad/plan-cuentas'
import { Route as AppContabilidadLibroContableRouteImport } from './routes/_app/contabilidad/libro-contable'
import { Route as AppContabilidadGastosDashboardRouteImport } from './routes/_app/contabilidad/gastos-dashboard'
import { Route as AppContabilidadGastosRouteImport } from './routes/_app/contabilidad/gastos'
import { Route as AppContabilidadCuentasConfigRouteImport } from './routes/_app/contabilidad/cuentas-config'
import { Route as AppContabilidadBalanceComprobacionRouteImport } from './routes/_app/contabilidad/balance-comprobacion'
import { Route as AppConfiguracionUsuariosRouteImport } from './routes/_app/configuracion/usuarios'
import { Route as AppConfiguracionTasaCambioRouteImport } from './routes/_app/configuracion/tasa-cambio'
import { Route as AppConfiguracionNivelesPrecioRouteImport } from './routes/_app/configuracion/niveles-precio'
import { Route as AppConfiguracionMetodosPagoRouteImport } from './routes/_app/configuracion/metodos-pago'
import { Route as AppConfiguracionImpuestosRouteImport } from './routes/_app/configuracion/impuestos'
import { Route as AppConfiguracionDatosEmpresaRouteImport } from './routes/_app/configuracion/datos-empresa'
import { Route as AppConfiguracionCajasRouteImport } from './routes/_app/configuracion/cajas'
import { Route as AppConfiguracionBancosRouteImport } from './routes/_app/configuracion/bancos'
import { Route as AppComprasRetencionesRouteImport } from './routes/_app/compras/retenciones'
import { Route as AppComprasNotasFiscalesRouteImport } from './routes/_app/compras/notas-fiscales'
import { Route as AppComprasGastosDashboardRouteImport } from './routes/_app/compras/gastos-dashboard'
import { Route as AppComprasGastosRouteImport } from './routes/_app/compras/gastos'
import { Route as AppComprasFacturasRouteImport } from './routes/_app/compras/facturas'
import { Route as AppComprasCxpRouteImport } from './routes/_app/compras/cxp'
import { Route as AppClientesReportesRouteImport } from './routes/_app/clientes/reportes'
import { Route as AppClientesGestionRouteImport } from './routes/_app/clientes/gestion'
import { Route as AppClientesCuentasPorCobrarRouteImport } from './routes/_app/clientes/cuentas-por-cobrar'
import { Route as AppCitasPanelRouteImport } from './routes/_app/citas/panel'
import { Route as AppCitasNuevaRouteImport } from './routes/_app/citas/nueva'
import { Route as AppCitasHorariosStaffRouteImport } from './routes/_app/citas/horarios-staff'
import { Route as AppCitasCalendarioRouteImport } from './routes/_app/citas/calendario'
import { Route as AppCajaSesionesRouteImport } from './routes/_app/caja/sesiones'
import { Route as AppCajaRendimientoRouteImport } from './routes/_app/caja/rendimiento'
import { Route as AppCajaMovimientosRouteImport } from './routes/_app/caja/movimientos'
import { Route as AppBancosDiferencialCambiarioRouteImport } from './routes/_app/bancos/diferencial-cambiario'
import { Route as AppBancosConciliacionRouteImport } from './routes/_app/bancos/conciliacion'
import { Route as AppConfiguracionUsuariosIndexRouteImport } from './routes/_app/configuracion/usuarios/index'
import { Route as AppConfiguracionUsuariosNuevoRouteImport } from './routes/_app/configuracion/usuarios/nuevo'
import { Route as AppConfiguracionUsuariosUsuarioIdEditarRouteImport } from './routes/_app/configuracion/usuarios/$usuarioId.editar'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCxcRoute = AppCxcRouteImport.update({
  id: '/cxc',
  path: '/cxc',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClinicaRoute = AppClinicaRouteImport.update({
  id: '/clinica',
  path: '/clinica',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const AppCitasRouteRoute = AppCitasRouteRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTesoreriaIndexRoute = AppTesoreriaIndexRouteImport.update({
  id: '/tesoreria/',
  path: '/tesoreria/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppCitasIndexRoute = AppCitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCitasRouteRoute,
} as any)
const AppVentasReportesRoute = AppVentasReportesRouteImport.update({
  id: '/ventas/reportes',
  path: '/ventas/reportes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVentasPrestamosRoute = AppVentasPrestamosRouteImport.update({
  id: '/ventas/prestamos',
  path: '/ventas/prestamos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVentasNuevaRoute = AppVentasNuevaRouteImport.update({
  id: '/ventas/nueva',
  path: '/ventas/nueva',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVentasFacturasEmitidasRoute =
  AppVentasFacturasEmitidasRouteImport.update({
    id: '/ventas/facturas-emitidas',
    path: '/ventas/facturas-emitidas',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppVentasCuadreDeCajaRoute = AppVentasCuadreDeCajaRouteImport.update({
  id: '/ventas/cuadre-de-caja',
  path: '/ventas/cuadre-de-caja',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProveedoresGestionRoute = AppProveedoresGestionRouteImport.update({
  id: '/proveedores/gestion',
  path: '/proveedores/gestion',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioUnidadesRoute = AppInventarioUnidadesRouteImport.update({
  id: '/inventario/unidades',
  path: '/inventario/unidades',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioTraspasosRoute = AppInventarioTraspasosRouteImport.update({
  id: '/inventario/traspasos',
  path: '/inventario/traspasos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioReportesRoute = AppInventarioReportesRouteImport.update({
  id: '/inventario/reportes',
  path: '/inventario/reportes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioRecetasRoute = AppInventarioRecetasRouteImport.update({
  id: '/inventario/recetas',
  path: '/inventario/recetas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioProductosRoute = AppInventarioProductosRouteImport.update({
  id: '/inventario/productos',
  path: '/inventario/productos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioMarcasRoute = AppInventarioMarcasRouteImport.update({
  id: '/inventario/marcas',
  path: '/inventario/marcas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioLotesRoute = AppInventarioLotesRouteImport.update({
  id: '/inventario/lotes',
  path: '/inventario/lotes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioKardexRoute = AppInventarioKardexRouteImport.update({
  id: '/inventario/kardex',
  path: '/inventario/kardex',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioDepositosRoute = AppInventarioDepositosRouteImport.update({
  id: '/inventario/depositos',
  path: '/inventario/depositos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioDepartamentosRoute =
  AppInventarioDepartamentosRouteImport.update({
    id: '/inventario/departamentos',
    path: '/inventario/departamentos',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInventarioComprasRoute = AppInventarioComprasRouteImport.update({
  id: '/inventario/compras',
  path: '/inventario/compras',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioAjustesRoute = AppInventarioAjustesRouteImport.update({
  id: '/inventario/ajustes',
  path: '/inventario/ajustes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContabilidadPlanCuentasRoute =
  AppContabilidadPlanCuentasRouteImport.update({
    id: '/contabilidad/plan-cuentas',
    path: '/contabilidad/plan-cuentas',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppContabilidadLibroContableRoute =
  AppContabilidadLibroContableRouteImport.update({
    id: '/contabilidad/libro-contable',
    path: '/contabilidad/libro-contable',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppContabilidadGastosDashboardRoute =
  AppContabilidadGastosDashboardRouteImport.update({
    id: '/contabilidad/gastos-dashboard',
    path: '/contabilidad/gastos-dashboard',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppContabilidadGastosRoute = AppContabilidadGastosRouteImport.update({
  id: '/contabilidad/gastos',
  path: '/contabilidad/gastos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContabilidadCuentasConfigRoute =
  AppContabilidadCuentasConfigRouteImport.update({
    id: '/contabilidad/cuentas-config',
    path: '/contabilidad/cuentas-config',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppContabilidadBalanceComprobacionRoute =
  AppContabilidadBalanceComprobacionRouteImport.update({
    id: '/contabilidad/balance-comprobacion',
    path: '/contabilidad/balance-comprobacion',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionUsuariosRoute =
  AppConfiguracionUsuariosRouteImport.update({
    id: '/configuracion/usuarios',
    path: '/configuracion/usuarios',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionTasaCambioRoute =
  AppConfiguracionTasaCambioRouteImport.update({
    id: '/configuracion/tasa-cambio',
    path: '/configuracion/tasa-cambio',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionNivelesPrecioRoute =
  AppConfiguracionNivelesPrecioRouteImport.update({
    id: '/configuracion/niveles-precio',
    path: '/configuracion/niveles-precio',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionMetodosPagoRoute =
  AppConfiguracionMetodosPagoRouteImport.update({
    id: '/configuracion/metodos-pago',
    path: '/configuracion/metodos-pago',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionImpuestosRoute =
  AppConfiguracionImpuestosRouteImport.update({
    id: '/configuracion/impuestos',
    path: '/configuracion/impuestos',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionDatosEmpresaRoute =
  AppConfiguracionDatosEmpresaRouteImport.update({
    id: '/configuracion/datos-empresa',
    path: '/configuracion/datos-empresa',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionCajasRoute = AppConfiguracionCajasRouteImport.update({
  id: '/configuracion/cajas',
  path: '/configuracion/cajas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracionBancosRoute = AppConfiguracionBancosRouteImport.update({
  id: '/configuracion/bancos',
  path: '/configuracion/bancos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComprasRetencionesRoute = AppComprasRetencionesRouteImport.update({
  id: '/compras/retenciones',
  path: '/compras/retenciones',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComprasNotasFiscalesRoute = AppComprasNotasFiscalesRouteImport.update({
  id: '/compras/notas-fiscales',
  path: '/compras/notas-fiscales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComprasGastosDashboardRoute =
  AppComprasGastosDashboardRouteImport.update({
    id: '/compras/gastos-dashboard',
    path: '/compras/gastos-dashboard',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppComprasGastosRoute = AppComprasGastosRouteImport.update({
  id: '/compras/gastos',
  path: '/compras/gastos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComprasFacturasRoute = AppComprasFacturasRouteImport.update({
  id: '/compras/facturas',
  path: '/compras/facturas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComprasCxpRoute = AppComprasCxpRouteImport.update({
  id: '/compras/cxp',
  path: '/compras/cxp',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesReportesRoute = AppClientesReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesGestionRoute = AppClientesGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesCuentasPorCobrarRoute =
  AppClientesCuentasPorCobrarRouteImport.update({
    id: '/cuentas-por-cobrar',
    path: '/cuentas-por-cobrar',
    getParentRoute: () => AppClientesRoute,
  } as any)
const AppCitasPanelRoute = AppCitasPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AppCitasRouteRoute,
} as any)
const AppCitasNuevaRoute = AppCitasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppCitasRouteRoute,
} as any)
const AppCitasHorariosStaffRoute = AppCitasHorariosStaffRouteImport.update({
  id: '/horarios-staff',
  path: '/horarios-staff',
  getParentRoute: () => AppCitasRouteRoute,
} as any)
const AppCitasCalendarioRoute = AppCitasCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppCitasRouteRoute,
} as any)
const AppCajaSesionesRoute = AppCajaSesionesRouteImport.update({
  id: '/caja/sesiones',
  path: '/caja/sesiones',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCajaRendimientoRoute = AppCajaRendimientoRouteImport.update({
  id: '/caja/rendimiento',
  path: '/caja/rendimiento',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCajaMovimientosRoute = AppCajaMovimientosRouteImport.update({
  id: '/caja/movimientos',
  path: '/caja/movimientos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBancosDiferencialCambiarioRoute =
  AppBancosDiferencialCambiarioRouteImport.update({
    id: '/bancos/diferencial-cambiario',
    path: '/bancos/diferencial-cambiario',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBancosConciliacionRoute = AppBancosConciliacionRouteImport.update({
  id: '/bancos/conciliacion',
  path: '/bancos/conciliacion',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracionUsuariosIndexRoute =
  AppConfiguracionUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppConfiguracionUsuariosRoute,
  } as any)
const AppConfiguracionUsuariosNuevoRoute =
  AppConfiguracionUsuariosNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AppConfiguracionUsuariosRoute,
  } as any)
const AppConfiguracionUsuariosUsuarioIdEditarRoute =
  AppConfiguracionUsuariosUsuarioIdEditarRouteImport.update({
    id: '/$usuarioId/editar',
    path: '/$usuarioId/editar',
    getParentRoute: () => AppConfiguracionUsuariosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citas': typeof AppCitasRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/clinica': typeof AppClinicaRoute
  '/cxc': typeof AppCxcRoute
  '/dashboard': typeof AppDashboardRoute
  '/perfil': typeof AppPerfilRoute
  '/reportes': typeof AppReportesRoute
  '/bancos/conciliacion': typeof AppBancosConciliacionRoute
  '/bancos/diferencial-cambiario': typeof AppBancosDiferencialCambiarioRoute
  '/caja/movimientos': typeof AppCajaMovimientosRoute
  '/caja/rendimiento': typeof AppCajaRendimientoRoute
  '/caja/sesiones': typeof AppCajaSesionesRoute
  '/citas/calendario': typeof AppCitasCalendarioRoute
  '/citas/horarios-staff': typeof AppCitasHorariosStaffRoute
  '/citas/nueva': typeof AppCitasNuevaRoute
  '/citas/panel': typeof AppCitasPanelRoute
  '/clientes/cuentas-por-cobrar': typeof AppClientesCuentasPorCobrarRoute
  '/clientes/gestion': typeof AppClientesGestionRoute
  '/clientes/reportes': typeof AppClientesReportesRoute
  '/compras/cxp': typeof AppComprasCxpRoute
  '/compras/facturas': typeof AppComprasFacturasRoute
  '/compras/gastos': typeof AppComprasGastosRoute
  '/compras/gastos-dashboard': typeof AppComprasGastosDashboardRoute
  '/compras/notas-fiscales': typeof AppComprasNotasFiscalesRoute
  '/compras/retenciones': typeof AppComprasRetencionesRoute
  '/configuracion/bancos': typeof AppConfiguracionBancosRoute
  '/configuracion/cajas': typeof AppConfiguracionCajasRoute
  '/configuracion/datos-empresa': typeof AppConfiguracionDatosEmpresaRoute
  '/configuracion/impuestos': typeof AppConfiguracionImpuestosRoute
  '/configuracion/metodos-pago': typeof AppConfiguracionMetodosPagoRoute
  '/configuracion/niveles-precio': typeof AppConfiguracionNivelesPrecioRoute
  '/configuracion/tasa-cambio': typeof AppConfiguracionTasaCambioRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRouteWithChildren
  '/contabilidad/balance-comprobacion': typeof AppContabilidadBalanceComprobacionRoute
  '/contabilidad/cuentas-config': typeof AppContabilidadCuentasConfigRoute
  '/contabilidad/gastos': typeof AppContabilidadGastosRoute
  '/contabilidad/gastos-dashboard': typeof AppContabilidadGastosDashboardRoute
  '/contabilidad/libro-contable': typeof AppContabilidadLibroContableRoute
  '/contabilidad/plan-cuentas': typeof AppContabilidadPlanCuentasRoute
  '/inventario/ajustes': typeof AppInventarioAjustesRoute
  '/inventario/compras': typeof AppInventarioComprasRoute
  '/inventario/departamentos': typeof AppInventarioDepartamentosRoute
  '/inventario/depositos': typeof AppInventarioDepositosRoute
  '/inventario/kardex': typeof AppInventarioKardexRoute
  '/inventario/lotes': typeof AppInventarioLotesRoute
  '/inventario/marcas': typeof AppInventarioMarcasRoute
  '/inventario/productos': typeof AppInventarioProductosRoute
  '/inventario/recetas': typeof AppInventarioRecetasRoute
  '/inventario/reportes': typeof AppInventarioReportesRoute
  '/inventario/traspasos': typeof AppInventarioTraspasosRoute
  '/inventario/unidades': typeof AppInventarioUnidadesRoute
  '/proveedores/gestion': typeof AppProveedoresGestionRoute
  '/ventas/cuadre-de-caja': typeof AppVentasCuadreDeCajaRoute
  '/ventas/facturas-emitidas': typeof AppVentasFacturasEmitidasRoute
  '/ventas/nueva': typeof AppVentasNuevaRoute
  '/ventas/prestamos': typeof AppVentasPrestamosRoute
  '/ventas/reportes': typeof AppVentasReportesRoute
  '/citas/': typeof AppCitasIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/tesoreria/': typeof AppTesoreriaIndexRoute
  '/configuracion/usuarios/nuevo': typeof AppConfiguracionUsuariosNuevoRoute
  '/configuracion/usuarios/': typeof AppConfiguracionUsuariosIndexRoute
  '/configuracion/usuarios/$usuarioId/editar': typeof AppConfiguracionUsuariosUsuarioIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/clinica': typeof AppClinicaRoute
  '/cxc': typeof AppCxcRoute
  '/dashboard': typeof AppDashboardRoute
  '/perfil': typeof AppPerfilRoute
  '/reportes': typeof AppReportesRoute
  '/bancos/conciliacion': typeof AppBancosConciliacionRoute
  '/bancos/diferencial-cambiario': typeof AppBancosDiferencialCambiarioRoute
  '/caja/movimientos': typeof AppCajaMovimientosRoute
  '/caja/rendimiento': typeof AppCajaRendimientoRoute
  '/caja/sesiones': typeof AppCajaSesionesRoute
  '/citas/calendario': typeof AppCitasCalendarioRoute
  '/citas/horarios-staff': typeof AppCitasHorariosStaffRoute
  '/citas/nueva': typeof AppCitasNuevaRoute
  '/citas/panel': typeof AppCitasPanelRoute
  '/clientes/cuentas-por-cobrar': typeof AppClientesCuentasPorCobrarRoute
  '/clientes/gestion': typeof AppClientesGestionRoute
  '/clientes/reportes': typeof AppClientesReportesRoute
  '/compras/cxp': typeof AppComprasCxpRoute
  '/compras/facturas': typeof AppComprasFacturasRoute
  '/compras/gastos': typeof AppComprasGastosRoute
  '/compras/gastos-dashboard': typeof AppComprasGastosDashboardRoute
  '/compras/notas-fiscales': typeof AppComprasNotasFiscalesRoute
  '/compras/retenciones': typeof AppComprasRetencionesRoute
  '/configuracion/bancos': typeof AppConfiguracionBancosRoute
  '/configuracion/cajas': typeof AppConfiguracionCajasRoute
  '/configuracion/datos-empresa': typeof AppConfiguracionDatosEmpresaRoute
  '/configuracion/impuestos': typeof AppConfiguracionImpuestosRoute
  '/configuracion/metodos-pago': typeof AppConfiguracionMetodosPagoRoute
  '/configuracion/niveles-precio': typeof AppConfiguracionNivelesPrecioRoute
  '/configuracion/tasa-cambio': typeof AppConfiguracionTasaCambioRoute
  '/contabilidad/balance-comprobacion': typeof AppContabilidadBalanceComprobacionRoute
  '/contabilidad/cuentas-config': typeof AppContabilidadCuentasConfigRoute
  '/contabilidad/gastos': typeof AppContabilidadGastosRoute
  '/contabilidad/gastos-dashboard': typeof AppContabilidadGastosDashboardRoute
  '/contabilidad/libro-contable': typeof AppContabilidadLibroContableRoute
  '/contabilidad/plan-cuentas': typeof AppContabilidadPlanCuentasRoute
  '/inventario/ajustes': typeof AppInventarioAjustesRoute
  '/inventario/compras': typeof AppInventarioComprasRoute
  '/inventario/departamentos': typeof AppInventarioDepartamentosRoute
  '/inventario/depositos': typeof AppInventarioDepositosRoute
  '/inventario/kardex': typeof AppInventarioKardexRoute
  '/inventario/lotes': typeof AppInventarioLotesRoute
  '/inventario/marcas': typeof AppInventarioMarcasRoute
  '/inventario/productos': typeof AppInventarioProductosRoute
  '/inventario/recetas': typeof AppInventarioRecetasRoute
  '/inventario/reportes': typeof AppInventarioReportesRoute
  '/inventario/traspasos': typeof AppInventarioTraspasosRoute
  '/inventario/unidades': typeof AppInventarioUnidadesRoute
  '/proveedores/gestion': typeof AppProveedoresGestionRoute
  '/ventas/cuadre-de-caja': typeof AppVentasCuadreDeCajaRoute
  '/ventas/facturas-emitidas': typeof AppVentasFacturasEmitidasRoute
  '/ventas/nueva': typeof AppVentasNuevaRoute
  '/ventas/prestamos': typeof AppVentasPrestamosRoute
  '/ventas/reportes': typeof AppVentasReportesRoute
  '/citas': typeof AppCitasIndexRoute
  '/clientes': typeof AppClientesIndexRoute
  '/tesoreria': typeof AppTesoreriaIndexRoute
  '/configuracion/usuarios/nuevo': typeof AppConfiguracionUsuariosNuevoRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosIndexRoute
  '/configuracion/usuarios/$usuarioId/editar': typeof AppConfiguracionUsuariosUsuarioIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/citas': typeof AppCitasRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/clinica': typeof AppClinicaRoute
  '/_app/cxc': typeof AppCxcRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/bancos/conciliacion': typeof AppBancosConciliacionRoute
  '/_app/bancos/diferencial-cambiario': typeof AppBancosDiferencialCambiarioRoute
  '/_app/caja/movimientos': typeof AppCajaMovimientosRoute
  '/_app/caja/rendimiento': typeof AppCajaRendimientoRoute
  '/_app/caja/sesiones': typeof AppCajaSesionesRoute
  '/_app/citas/calendario': typeof AppCitasCalendarioRoute
  '/_app/citas/horarios-staff': typeof AppCitasHorariosStaffRoute
  '/_app/citas/nueva': typeof AppCitasNuevaRoute
  '/_app/citas/panel': typeof AppCitasPanelRoute
  '/_app/clientes/cuentas-por-cobrar': typeof AppClientesCuentasPorCobrarRoute
  '/_app/clientes/gestion': typeof AppClientesGestionRoute
  '/_app/clientes/reportes': typeof AppClientesReportesRoute
  '/_app/compras/cxp': typeof AppComprasCxpRoute
  '/_app/compras/facturas': typeof AppComprasFacturasRoute
  '/_app/compras/gastos': typeof AppComprasGastosRoute
  '/_app/compras/gastos-dashboard': typeof AppComprasGastosDashboardRoute
  '/_app/compras/notas-fiscales': typeof AppComprasNotasFiscalesRoute
  '/_app/compras/retenciones': typeof AppComprasRetencionesRoute
  '/_app/configuracion/bancos': typeof AppConfiguracionBancosRoute
  '/_app/configuracion/cajas': typeof AppConfiguracionCajasRoute
  '/_app/configuracion/datos-empresa': typeof AppConfiguracionDatosEmpresaRoute
  '/_app/configuracion/impuestos': typeof AppConfiguracionImpuestosRoute
  '/_app/configuracion/metodos-pago': typeof AppConfiguracionMetodosPagoRoute
  '/_app/configuracion/niveles-precio': typeof AppConfiguracionNivelesPrecioRoute
  '/_app/configuracion/tasa-cambio': typeof AppConfiguracionTasaCambioRoute
  '/_app/configuracion/usuarios': typeof AppConfiguracionUsuariosRouteWithChildren
  '/_app/contabilidad/balance-comprobacion': typeof AppContabilidadBalanceComprobacionRoute
  '/_app/contabilidad/cuentas-config': typeof AppContabilidadCuentasConfigRoute
  '/_app/contabilidad/gastos': typeof AppContabilidadGastosRoute
  '/_app/contabilidad/gastos-dashboard': typeof AppContabilidadGastosDashboardRoute
  '/_app/contabilidad/libro-contable': typeof AppContabilidadLibroContableRoute
  '/_app/contabilidad/plan-cuentas': typeof AppContabilidadPlanCuentasRoute
  '/_app/inventario/ajustes': typeof AppInventarioAjustesRoute
  '/_app/inventario/compras': typeof AppInventarioComprasRoute
  '/_app/inventario/departamentos': typeof AppInventarioDepartamentosRoute
  '/_app/inventario/depositos': typeof AppInventarioDepositosRoute
  '/_app/inventario/kardex': typeof AppInventarioKardexRoute
  '/_app/inventario/lotes': typeof AppInventarioLotesRoute
  '/_app/inventario/marcas': typeof AppInventarioMarcasRoute
  '/_app/inventario/productos': typeof AppInventarioProductosRoute
  '/_app/inventario/recetas': typeof AppInventarioRecetasRoute
  '/_app/inventario/reportes': typeof AppInventarioReportesRoute
  '/_app/inventario/traspasos': typeof AppInventarioTraspasosRoute
  '/_app/inventario/unidades': typeof AppInventarioUnidadesRoute
  '/_app/proveedores/gestion': typeof AppProveedoresGestionRoute
  '/_app/ventas/cuadre-de-caja': typeof AppVentasCuadreDeCajaRoute
  '/_app/ventas/facturas-emitidas': typeof AppVentasFacturasEmitidasRoute
  '/_app/ventas/nueva': typeof AppVentasNuevaRoute
  '/_app/ventas/prestamos': typeof AppVentasPrestamosRoute
  '/_app/ventas/reportes': typeof AppVentasReportesRoute
  '/_app/citas/': typeof AppCitasIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/tesoreria/': typeof AppTesoreriaIndexRoute
  '/_app/configuracion/usuarios/nuevo': typeof AppConfiguracionUsuariosNuevoRoute
  '/_app/configuracion/usuarios/': typeof AppConfiguracionUsuariosIndexRoute
  '/_app/configuracion/usuarios/$usuarioId/editar': typeof AppConfiguracionUsuariosUsuarioIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citas'
    | '/login'
    | '/register'
    | '/clientes'
    | '/clinica'
    | '/cxc'
    | '/dashboard'
    | '/perfil'
    | '/reportes'
    | '/bancos/conciliacion'
    | '/bancos/diferencial-cambiario'
    | '/caja/movimientos'
    | '/caja/rendimiento'
    | '/caja/sesiones'
    | '/citas/calendario'
    | '/citas/horarios-staff'
    | '/citas/nueva'
    | '/citas/panel'
    | '/clientes/cuentas-por-cobrar'
    | '/clientes/gestion'
    | '/clientes/reportes'
    | '/compras/cxp'
    | '/compras/facturas'
    | '/compras/gastos'
    | '/compras/gastos-dashboard'
    | '/compras/notas-fiscales'
    | '/compras/retenciones'
    | '/configuracion/bancos'
    | '/configuracion/cajas'
    | '/configuracion/datos-empresa'
    | '/configuracion/impuestos'
    | '/configuracion/metodos-pago'
    | '/configuracion/niveles-precio'
    | '/configuracion/tasa-cambio'
    | '/configuracion/usuarios'
    | '/contabilidad/balance-comprobacion'
    | '/contabilidad/cuentas-config'
    | '/contabilidad/gastos'
    | '/contabilidad/gastos-dashboard'
    | '/contabilidad/libro-contable'
    | '/contabilidad/plan-cuentas'
    | '/inventario/ajustes'
    | '/inventario/compras'
    | '/inventario/departamentos'
    | '/inventario/depositos'
    | '/inventario/kardex'
    | '/inventario/lotes'
    | '/inventario/marcas'
    | '/inventario/productos'
    | '/inventario/recetas'
    | '/inventario/reportes'
    | '/inventario/traspasos'
    | '/inventario/unidades'
    | '/proveedores/gestion'
    | '/ventas/cuadre-de-caja'
    | '/ventas/facturas-emitidas'
    | '/ventas/nueva'
    | '/ventas/prestamos'
    | '/ventas/reportes'
    | '/citas/'
    | '/clientes/'
    | '/tesoreria/'
    | '/configuracion/usuarios/nuevo'
    | '/configuracion/usuarios/'
    | '/configuracion/usuarios/$usuarioId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/clinica'
    | '/cxc'
    | '/dashboard'
    | '/perfil'
    | '/reportes'
    | '/bancos/conciliacion'
    | '/bancos/diferencial-cambiario'
    | '/caja/movimientos'
    | '/caja/rendimiento'
    | '/caja/sesiones'
    | '/citas/calendario'
    | '/citas/horarios-staff'
    | '/citas/nueva'
    | '/citas/panel'
    | '/clientes/cuentas-por-cobrar'
    | '/clientes/gestion'
    | '/clientes/reportes'
    | '/compras/cxp'
    | '/compras/facturas'
    | '/compras/gastos'
    | '/compras/gastos-dashboard'
    | '/compras/notas-fiscales'
    | '/compras/retenciones'
    | '/configuracion/bancos'
    | '/configuracion/cajas'
    | '/configuracion/datos-empresa'
    | '/configuracion/impuestos'
    | '/configuracion/metodos-pago'
    | '/configuracion/niveles-precio'
    | '/configuracion/tasa-cambio'
    | '/contabilidad/balance-comprobacion'
    | '/contabilidad/cuentas-config'
    | '/contabilidad/gastos'
    | '/contabilidad/gastos-dashboard'
    | '/contabilidad/libro-contable'
    | '/contabilidad/plan-cuentas'
    | '/inventario/ajustes'
    | '/inventario/compras'
    | '/inventario/departamentos'
    | '/inventario/depositos'
    | '/inventario/kardex'
    | '/inventario/lotes'
    | '/inventario/marcas'
    | '/inventario/productos'
    | '/inventario/recetas'
    | '/inventario/reportes'
    | '/inventario/traspasos'
    | '/inventario/unidades'
    | '/proveedores/gestion'
    | '/ventas/cuadre-de-caja'
    | '/ventas/facturas-emitidas'
    | '/ventas/nueva'
    | '/ventas/prestamos'
    | '/ventas/reportes'
    | '/citas'
    | '/clientes'
    | '/tesoreria'
    | '/configuracion/usuarios/nuevo'
    | '/configuracion/usuarios'
    | '/configuracion/usuarios/$usuarioId/editar'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_app'
    | '/_app/citas'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_app/clientes'
    | '/_app/clinica'
    | '/_app/cxc'
    | '/_app/dashboard'
    | '/_app/perfil'
    | '/_app/reportes'
    | '/_app/bancos/conciliacion'
    | '/_app/bancos/diferencial-cambiario'
    | '/_app/caja/movimientos'
    | '/_app/caja/rendimiento'
    | '/_app/caja/sesiones'
    | '/_app/citas/calendario'
    | '/_app/citas/horarios-staff'
    | '/_app/citas/nueva'
    | '/_app/citas/panel'
    | '/_app/clientes/cuentas-por-cobrar'
    | '/_app/clientes/gestion'
    | '/_app/clientes/reportes'
    | '/_app/compras/cxp'
    | '/_app/compras/facturas'
    | '/_app/compras/gastos'
    | '/_app/compras/gastos-dashboard'
    | '/_app/compras/notas-fiscales'
    | '/_app/compras/retenciones'
    | '/_app/configuracion/bancos'
    | '/_app/configuracion/cajas'
    | '/_app/configuracion/datos-empresa'
    | '/_app/configuracion/impuestos'
    | '/_app/configuracion/metodos-pago'
    | '/_app/configuracion/niveles-precio'
    | '/_app/configuracion/tasa-cambio'
    | '/_app/configuracion/usuarios'
    | '/_app/contabilidad/balance-comprobacion'
    | '/_app/contabilidad/cuentas-config'
    | '/_app/contabilidad/gastos'
    | '/_app/contabilidad/gastos-dashboard'
    | '/_app/contabilidad/libro-contable'
    | '/_app/contabilidad/plan-cuentas'
    | '/_app/inventario/ajustes'
    | '/_app/inventario/compras'
    | '/_app/inventario/departamentos'
    | '/_app/inventario/depositos'
    | '/_app/inventario/kardex'
    | '/_app/inventario/lotes'
    | '/_app/inventario/marcas'
    | '/_app/inventario/productos'
    | '/_app/inventario/recetas'
    | '/_app/inventario/reportes'
    | '/_app/inventario/traspasos'
    | '/_app/inventario/unidades'
    | '/_app/proveedores/gestion'
    | '/_app/ventas/cuadre-de-caja'
    | '/_app/ventas/facturas-emitidas'
    | '/_app/ventas/nueva'
    | '/_app/ventas/prestamos'
    | '/_app/ventas/reportes'
    | '/_app/citas/'
    | '/_app/clientes/'
    | '/_app/tesoreria/'
    | '/_app/configuracion/usuarios/nuevo'
    | '/_app/configuracion/usuarios/'
    | '/_app/configuracion/usuarios/$usuarioId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cxc': {
      id: '/_app/cxc'
      path: '/cxc'
      fullPath: '/cxc'
      preLoaderRoute: typeof AppCxcRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clinica': {
      id: '/_app/clinica'
      path: '/clinica'
      fullPath: '/clinica'
      preLoaderRoute: typeof AppClinicaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_app/citas': {
      id: '/_app/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof AppCitasRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tesoreria/': {
      id: '/_app/tesoreria/'
      path: '/tesoreria'
      fullPath: '/tesoreria/'
      preLoaderRoute: typeof AppTesoreriaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/citas/': {
      id: '/_app/citas/'
      path: '/'
      fullPath: '/citas/'
      preLoaderRoute: typeof AppCitasIndexRouteImport
      parentRoute: typeof AppCitasRouteRoute
    }
    '/_app/ventas/reportes': {
      id: '/_app/ventas/reportes'
      path: '/ventas/reportes'
      fullPath: '/ventas/reportes'
      preLoaderRoute: typeof AppVentasReportesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ventas/prestamos': {
      id: '/_app/ventas/prestamos'
      path: '/ventas/prestamos'
      fullPath: '/ventas/prestamos'
      preLoaderRoute: typeof AppVentasPrestamosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ventas/nueva': {
      id: '/_app/ventas/nueva'
      path: '/ventas/nueva'
      fullPath: '/ventas/nueva'
      preLoaderRoute: typeof AppVentasNuevaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ventas/facturas-emitidas': {
      id: '/_app/ventas/facturas-emitidas'
      path: '/ventas/facturas-emitidas'
      fullPath: '/ventas/facturas-emitidas'
      preLoaderRoute: typeof AppVentasFacturasEmitidasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ventas/cuadre-de-caja': {
      id: '/_app/ventas/cuadre-de-caja'
      path: '/ventas/cuadre-de-caja'
      fullPath: '/ventas/cuadre-de-caja'
      preLoaderRoute: typeof AppVentasCuadreDeCajaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/proveedores/gestion': {
      id: '/_app/proveedores/gestion'
      path: '/proveedores/gestion'
      fullPath: '/proveedores/gestion'
      preLoaderRoute: typeof AppProveedoresGestionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/unidades': {
      id: '/_app/inventario/unidades'
      path: '/inventario/unidades'
      fullPath: '/inventario/unidades'
      preLoaderRoute: typeof AppInventarioUnidadesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/traspasos': {
      id: '/_app/inventario/traspasos'
      path: '/inventario/traspasos'
      fullPath: '/inventario/traspasos'
      preLoaderRoute: typeof AppInventarioTraspasosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/reportes': {
      id: '/_app/inventario/reportes'
      path: '/inventario/reportes'
      fullPath: '/inventario/reportes'
      preLoaderRoute: typeof AppInventarioReportesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/recetas': {
      id: '/_app/inventario/recetas'
      path: '/inventario/recetas'
      fullPath: '/inventario/recetas'
      preLoaderRoute: typeof AppInventarioRecetasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/productos': {
      id: '/_app/inventario/productos'
      path: '/inventario/productos'
      fullPath: '/inventario/productos'
      preLoaderRoute: typeof AppInventarioProductosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/marcas': {
      id: '/_app/inventario/marcas'
      path: '/inventario/marcas'
      fullPath: '/inventario/marcas'
      preLoaderRoute: typeof AppInventarioMarcasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/lotes': {
      id: '/_app/inventario/lotes'
      path: '/inventario/lotes'
      fullPath: '/inventario/lotes'
      preLoaderRoute: typeof AppInventarioLotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/kardex': {
      id: '/_app/inventario/kardex'
      path: '/inventario/kardex'
      fullPath: '/inventario/kardex'
      preLoaderRoute: typeof AppInventarioKardexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/depositos': {
      id: '/_app/inventario/depositos'
      path: '/inventario/depositos'
      fullPath: '/inventario/depositos'
      preLoaderRoute: typeof AppInventarioDepositosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/departamentos': {
      id: '/_app/inventario/departamentos'
      path: '/inventario/departamentos'
      fullPath: '/inventario/departamentos'
      preLoaderRoute: typeof AppInventarioDepartamentosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/compras': {
      id: '/_app/inventario/compras'
      path: '/inventario/compras'
      fullPath: '/inventario/compras'
      preLoaderRoute: typeof AppInventarioComprasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/ajustes': {
      id: '/_app/inventario/ajustes'
      path: '/inventario/ajustes'
      fullPath: '/inventario/ajustes'
      preLoaderRoute: typeof AppInventarioAjustesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contabilidad/plan-cuentas': {
      id: '/_app/contabilidad/plan-cuentas'
      path: '/contabilidad/plan-cuentas'
      fullPath: '/contabilidad/plan-cuentas'
      preLoaderRoute: typeof AppContabilidadPlanCuentasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contabilidad/libro-contable': {
      id: '/_app/contabilidad/libro-contable'
      path: '/contabilidad/libro-contable'
      fullPath: '/contabilidad/libro-contable'
      preLoaderRoute: typeof AppContabilidadLibroContableRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contabilidad/gastos-dashboard': {
      id: '/_app/contabilidad/gastos-dashboard'
      path: '/contabilidad/gastos-dashboard'
      fullPath: '/contabilidad/gastos-dashboard'
      preLoaderRoute: typeof AppContabilidadGastosDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contabilidad/gastos': {
      id: '/_app/contabilidad/gastos'
      path: '/contabilidad/gastos'
      fullPath: '/contabilidad/gastos'
      preLoaderRoute: typeof AppContabilidadGastosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contabilidad/cuentas-config': {
      id: '/_app/contabilidad/cuentas-config'
      path: '/contabilidad/cuentas-config'
      fullPath: '/contabilidad/cuentas-config'
      preLoaderRoute: typeof AppContabilidadCuentasConfigRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contabilidad/balance-comprobacion': {
      id: '/_app/contabilidad/balance-comprobacion'
      path: '/contabilidad/balance-comprobacion'
      fullPath: '/contabilidad/balance-comprobacion'
      preLoaderRoute: typeof AppContabilidadBalanceComprobacionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/usuarios': {
      id: '/_app/configuracion/usuarios'
      path: '/configuracion/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AppConfiguracionUsuariosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/tasa-cambio': {
      id: '/_app/configuracion/tasa-cambio'
      path: '/configuracion/tasa-cambio'
      fullPath: '/configuracion/tasa-cambio'
      preLoaderRoute: typeof AppConfiguracionTasaCambioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/niveles-precio': {
      id: '/_app/configuracion/niveles-precio'
      path: '/configuracion/niveles-precio'
      fullPath: '/configuracion/niveles-precio'
      preLoaderRoute: typeof AppConfiguracionNivelesPrecioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/metodos-pago': {
      id: '/_app/configuracion/metodos-pago'
      path: '/configuracion/metodos-pago'
      fullPath: '/configuracion/metodos-pago'
      preLoaderRoute: typeof AppConfiguracionMetodosPagoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/impuestos': {
      id: '/_app/configuracion/impuestos'
      path: '/configuracion/impuestos'
      fullPath: '/configuracion/impuestos'
      preLoaderRoute: typeof AppConfiguracionImpuestosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/datos-empresa': {
      id: '/_app/configuracion/datos-empresa'
      path: '/configuracion/datos-empresa'
      fullPath: '/configuracion/datos-empresa'
      preLoaderRoute: typeof AppConfiguracionDatosEmpresaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/cajas': {
      id: '/_app/configuracion/cajas'
      path: '/configuracion/cajas'
      fullPath: '/configuracion/cajas'
      preLoaderRoute: typeof AppConfiguracionCajasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/bancos': {
      id: '/_app/configuracion/bancos'
      path: '/configuracion/bancos'
      fullPath: '/configuracion/bancos'
      preLoaderRoute: typeof AppConfiguracionBancosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compras/retenciones': {
      id: '/_app/compras/retenciones'
      path: '/compras/retenciones'
      fullPath: '/compras/retenciones'
      preLoaderRoute: typeof AppComprasRetencionesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compras/notas-fiscales': {
      id: '/_app/compras/notas-fiscales'
      path: '/compras/notas-fiscales'
      fullPath: '/compras/notas-fiscales'
      preLoaderRoute: typeof AppComprasNotasFiscalesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compras/gastos-dashboard': {
      id: '/_app/compras/gastos-dashboard'
      path: '/compras/gastos-dashboard'
      fullPath: '/compras/gastos-dashboard'
      preLoaderRoute: typeof AppComprasGastosDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compras/gastos': {
      id: '/_app/compras/gastos'
      path: '/compras/gastos'
      fullPath: '/compras/gastos'
      preLoaderRoute: typeof AppComprasGastosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compras/facturas': {
      id: '/_app/compras/facturas'
      path: '/compras/facturas'
      fullPath: '/compras/facturas'
      preLoaderRoute: typeof AppComprasFacturasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compras/cxp': {
      id: '/_app/compras/cxp'
      path: '/compras/cxp'
      fullPath: '/compras/cxp'
      preLoaderRoute: typeof AppComprasCxpRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clientes/reportes': {
      id: '/_app/clientes/reportes'
      path: '/reportes'
      fullPath: '/clientes/reportes'
      preLoaderRoute: typeof AppClientesReportesRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/clientes/gestion': {
      id: '/_app/clientes/gestion'
      path: '/gestion'
      fullPath: '/clientes/gestion'
      preLoaderRoute: typeof AppClientesGestionRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/clientes/cuentas-por-cobrar': {
      id: '/_app/clientes/cuentas-por-cobrar'
      path: '/cuentas-por-cobrar'
      fullPath: '/clientes/cuentas-por-cobrar'
      preLoaderRoute: typeof AppClientesCuentasPorCobrarRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/citas/panel': {
      id: '/_app/citas/panel'
      path: '/panel'
      fullPath: '/citas/panel'
      preLoaderRoute: typeof AppCitasPanelRouteImport
      parentRoute: typeof AppCitasRouteRoute
    }
    '/_app/citas/nueva': {
      id: '/_app/citas/nueva'
      path: '/nueva'
      fullPath: '/citas/nueva'
      preLoaderRoute: typeof AppCitasNuevaRouteImport
      parentRoute: typeof AppCitasRouteRoute
    }
    '/_app/citas/horarios-staff': {
      id: '/_app/citas/horarios-staff'
      path: '/horarios-staff'
      fullPath: '/citas/horarios-staff'
      preLoaderRoute: typeof AppCitasHorariosStaffRouteImport
      parentRoute: typeof AppCitasRouteRoute
    }
    '/_app/citas/calendario': {
      id: '/_app/citas/calendario'
      path: '/calendario'
      fullPath: '/citas/calendario'
      preLoaderRoute: typeof AppCitasCalendarioRouteImport
      parentRoute: typeof AppCitasRouteRoute
    }
    '/_app/caja/sesiones': {
      id: '/_app/caja/sesiones'
      path: '/caja/sesiones'
      fullPath: '/caja/sesiones'
      preLoaderRoute: typeof AppCajaSesionesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/caja/rendimiento': {
      id: '/_app/caja/rendimiento'
      path: '/caja/rendimiento'
      fullPath: '/caja/rendimiento'
      preLoaderRoute: typeof AppCajaRendimientoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/caja/movimientos': {
      id: '/_app/caja/movimientos'
      path: '/caja/movimientos'
      fullPath: '/caja/movimientos'
      preLoaderRoute: typeof AppCajaMovimientosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bancos/diferencial-cambiario': {
      id: '/_app/bancos/diferencial-cambiario'
      path: '/bancos/diferencial-cambiario'
      fullPath: '/bancos/diferencial-cambiario'
      preLoaderRoute: typeof AppBancosDiferencialCambiarioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bancos/conciliacion': {
      id: '/_app/bancos/conciliacion'
      path: '/bancos/conciliacion'
      fullPath: '/bancos/conciliacion'
      preLoaderRoute: typeof AppBancosConciliacionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/usuarios/': {
      id: '/_app/configuracion/usuarios/'
      path: '/'
      fullPath: '/configuracion/usuarios/'
      preLoaderRoute: typeof AppConfiguracionUsuariosIndexRouteImport
      parentRoute: typeof AppConfiguracionUsuariosRoute
    }
    '/_app/configuracion/usuarios/nuevo': {
      id: '/_app/configuracion/usuarios/nuevo'
      path: '/nuevo'
      fullPath: '/configuracion/usuarios/nuevo'
      preLoaderRoute: typeof AppConfiguracionUsuariosNuevoRouteImport
      parentRoute: typeof AppConfiguracionUsuariosRoute
    }
    '/_app/configuracion/usuarios/$usuarioId/editar': {
      id: '/_app/configuracion/usuarios/$usuarioId/editar'
      path: '/$usuarioId/editar'
      fullPath: '/configuracion/usuarios/$usuarioId/editar'
      preLoaderRoute: typeof AppConfiguracionUsuariosUsuarioIdEditarRouteImport
      parentRoute: typeof AppConfiguracionUsuariosRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppCitasRouteRouteChildren {
  AppCitasCalendarioRoute: typeof AppCitasCalendarioRoute
  AppCitasHorariosStaffRoute: typeof AppCitasHorariosStaffRoute
  AppCitasNuevaRoute: typeof AppCitasNuevaRoute
  AppCitasPanelRoute: typeof AppCitasPanelRoute
  AppCitasIndexRoute: typeof AppCitasIndexRoute
}

const AppCitasRouteRouteChildren: AppCitasRouteRouteChildren = {
  AppCitasCalendarioRoute: AppCitasCalendarioRoute,
  AppCitasHorariosStaffRoute: AppCitasHorariosStaffRoute,
  AppCitasNuevaRoute: AppCitasNuevaRoute,
  AppCitasPanelRoute: AppCitasPanelRoute,
  AppCitasIndexRoute: AppCitasIndexRoute,
}

const AppCitasRouteRouteWithChildren = AppCitasRouteRoute._addFileChildren(
  AppCitasRouteRouteChildren,
)

interface AppClientesRouteChildren {
  AppClientesCuentasPorCobrarRoute: typeof AppClientesCuentasPorCobrarRoute
  AppClientesGestionRoute: typeof AppClientesGestionRoute
  AppClientesReportesRoute: typeof AppClientesReportesRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesCuentasPorCobrarRoute: AppClientesCuentasPorCobrarRoute,
  AppClientesGestionRoute: AppClientesGestionRoute,
  AppClientesReportesRoute: AppClientesReportesRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppConfiguracionUsuariosRouteChildren {
  AppConfiguracionUsuariosNuevoRoute: typeof AppConfiguracionUsuariosNuevoRoute
  AppConfiguracionUsuariosIndexRoute: typeof AppConfiguracionUsuariosIndexRoute
  AppConfiguracionUsuariosUsuarioIdEditarRoute: typeof AppConfiguracionUsuariosUsuarioIdEditarRoute
}

const AppConfiguracionUsuariosRouteChildren: AppConfiguracionUsuariosRouteChildren =
  {
    AppConfiguracionUsuariosNuevoRoute: AppConfiguracionUsuariosNuevoRoute,
    AppConfiguracionUsuariosIndexRoute: AppConfiguracionUsuariosIndexRoute,
    AppConfiguracionUsuariosUsuarioIdEditarRoute:
      AppConfiguracionUsuariosUsuarioIdEditarRoute,
  }

const AppConfiguracionUsuariosRouteWithChildren =
  AppConfiguracionUsuariosRoute._addFileChildren(
    AppConfiguracionUsuariosRouteChildren,
  )

interface AppRouteRouteChildren {
  AppCitasRouteRoute: typeof AppCitasRouteRouteWithChildren
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppClinicaRoute: typeof AppClinicaRoute
  AppCxcRoute: typeof AppCxcRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppReportesRoute: typeof AppReportesRoute
  AppBancosConciliacionRoute: typeof AppBancosConciliacionRoute
  AppBancosDiferencialCambiarioRoute: typeof AppBancosDiferencialCambiarioRoute
  AppCajaMovimientosRoute: typeof AppCajaMovimientosRoute
  AppCajaRendimientoRoute: typeof AppCajaRendimientoRoute
  AppCajaSesionesRoute: typeof AppCajaSesionesRoute
  AppComprasCxpRoute: typeof AppComprasCxpRoute
  AppComprasFacturasRoute: typeof AppComprasFacturasRoute
  AppComprasGastosRoute: typeof AppComprasGastosRoute
  AppComprasGastosDashboardRoute: typeof AppComprasGastosDashboardRoute
  AppComprasNotasFiscalesRoute: typeof AppComprasNotasFiscalesRoute
  AppComprasRetencionesRoute: typeof AppComprasRetencionesRoute
  AppConfiguracionBancosRoute: typeof AppConfiguracionBancosRoute
  AppConfiguracionCajasRoute: typeof AppConfiguracionCajasRoute
  AppConfiguracionDatosEmpresaRoute: typeof AppConfiguracionDatosEmpresaRoute
  AppConfiguracionImpuestosRoute: typeof AppConfiguracionImpuestosRoute
  AppConfiguracionMetodosPagoRoute: typeof AppConfiguracionMetodosPagoRoute
  AppConfiguracionNivelesPrecioRoute: typeof AppConfiguracionNivelesPrecioRoute
  AppConfiguracionTasaCambioRoute: typeof AppConfiguracionTasaCambioRoute
  AppConfiguracionUsuariosRoute: typeof AppConfiguracionUsuariosRouteWithChildren
  AppContabilidadBalanceComprobacionRoute: typeof AppContabilidadBalanceComprobacionRoute
  AppContabilidadCuentasConfigRoute: typeof AppContabilidadCuentasConfigRoute
  AppContabilidadGastosRoute: typeof AppContabilidadGastosRoute
  AppContabilidadGastosDashboardRoute: typeof AppContabilidadGastosDashboardRoute
  AppContabilidadLibroContableRoute: typeof AppContabilidadLibroContableRoute
  AppContabilidadPlanCuentasRoute: typeof AppContabilidadPlanCuentasRoute
  AppInventarioAjustesRoute: typeof AppInventarioAjustesRoute
  AppInventarioComprasRoute: typeof AppInventarioComprasRoute
  AppInventarioDepartamentosRoute: typeof AppInventarioDepartamentosRoute
  AppInventarioDepositosRoute: typeof AppInventarioDepositosRoute
  AppInventarioKardexRoute: typeof AppInventarioKardexRoute
  AppInventarioLotesRoute: typeof AppInventarioLotesRoute
  AppInventarioMarcasRoute: typeof AppInventarioMarcasRoute
  AppInventarioProductosRoute: typeof AppInventarioProductosRoute
  AppInventarioRecetasRoute: typeof AppInventarioRecetasRoute
  AppInventarioReportesRoute: typeof AppInventarioReportesRoute
  AppInventarioTraspasosRoute: typeof AppInventarioTraspasosRoute
  AppInventarioUnidadesRoute: typeof AppInventarioUnidadesRoute
  AppProveedoresGestionRoute: typeof AppProveedoresGestionRoute
  AppVentasCuadreDeCajaRoute: typeof AppVentasCuadreDeCajaRoute
  AppVentasFacturasEmitidasRoute: typeof AppVentasFacturasEmitidasRoute
  AppVentasNuevaRoute: typeof AppVentasNuevaRoute
  AppVentasPrestamosRoute: typeof AppVentasPrestamosRoute
  AppVentasReportesRoute: typeof AppVentasReportesRoute
  AppTesoreriaIndexRoute: typeof AppTesoreriaIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCitasRouteRoute: AppCitasRouteRouteWithChildren,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppClinicaRoute: AppClinicaRoute,
  AppCxcRoute: AppCxcRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppReportesRoute: AppReportesRoute,
  AppBancosConciliacionRoute: AppBancosConciliacionRoute,
  AppBancosDiferencialCambiarioRoute: AppBancosDiferencialCambiarioRoute,
  AppCajaMovimientosRoute: AppCajaMovimientosRoute,
  AppCajaRendimientoRoute: AppCajaRendimientoRoute,
  AppCajaSesionesRoute: AppCajaSesionesRoute,
  AppComprasCxpRoute: AppComprasCxpRoute,
  AppComprasFacturasRoute: AppComprasFacturasRoute,
  AppComprasGastosRoute: AppComprasGastosRoute,
  AppComprasGastosDashboardRoute: AppComprasGastosDashboardRoute,
  AppComprasNotasFiscalesRoute: AppComprasNotasFiscalesRoute,
  AppComprasRetencionesRoute: AppComprasRetencionesRoute,
  AppConfiguracionBancosRoute: AppConfiguracionBancosRoute,
  AppConfiguracionCajasRoute: AppConfiguracionCajasRoute,
  AppConfiguracionDatosEmpresaRoute: AppConfiguracionDatosEmpresaRoute,
  AppConfiguracionImpuestosRoute: AppConfiguracionImpuestosRoute,
  AppConfiguracionMetodosPagoRoute: AppConfiguracionMetodosPagoRoute,
  AppConfiguracionNivelesPrecioRoute: AppConfiguracionNivelesPrecioRoute,
  AppConfiguracionTasaCambioRoute: AppConfiguracionTasaCambioRoute,
  AppConfiguracionUsuariosRoute: AppConfiguracionUsuariosRouteWithChildren,
  AppContabilidadBalanceComprobacionRoute:
    AppContabilidadBalanceComprobacionRoute,
  AppContabilidadCuentasConfigRoute: AppContabilidadCuentasConfigRoute,
  AppContabilidadGastosRoute: AppContabilidadGastosRoute,
  AppContabilidadGastosDashboardRoute: AppContabilidadGastosDashboardRoute,
  AppContabilidadLibroContableRoute: AppContabilidadLibroContableRoute,
  AppContabilidadPlanCuentasRoute: AppContabilidadPlanCuentasRoute,
  AppInventarioAjustesRoute: AppInventarioAjustesRoute,
  AppInventarioComprasRoute: AppInventarioComprasRoute,
  AppInventarioDepartamentosRoute: AppInventarioDepartamentosRoute,
  AppInventarioDepositosRoute: AppInventarioDepositosRoute,
  AppInventarioKardexRoute: AppInventarioKardexRoute,
  AppInventarioLotesRoute: AppInventarioLotesRoute,
  AppInventarioMarcasRoute: AppInventarioMarcasRoute,
  AppInventarioProductosRoute: AppInventarioProductosRoute,
  AppInventarioRecetasRoute: AppInventarioRecetasRoute,
  AppInventarioReportesRoute: AppInventarioReportesRoute,
  AppInventarioTraspasosRoute: AppInventarioTraspasosRoute,
  AppInventarioUnidadesRoute: AppInventarioUnidadesRoute,
  AppProveedoresGestionRoute: AppProveedoresGestionRoute,
  AppVentasCuadreDeCajaRoute: AppVentasCuadreDeCajaRoute,
  AppVentasFacturasEmitidasRoute: AppVentasFacturasEmitidasRoute,
  AppVentasNuevaRoute: AppVentasNuevaRoute,
  AppVentasPrestamosRoute: AppVentasPrestamosRoute,
  AppVentasReportesRoute: AppVentasReportesRoute,
  AppTesoreriaIndexRoute: AppTesoreriaIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
